-- Carguvi core schema
-- Multi-vendor vehicle-parts marketplace for Zimbabwe.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

create type app_role as enum (
  'super_admin',
  'admin',
  'vendor',
  'staff',
  'enumerator',
  'customer'
);

create type vendor_status as enum ('pending', 'approved', 'suspended', 'rejected');

create type product_condition as enum ('new', 'used', 'refurbished');

create type availability_status as enum (
  'in_stock',
  'low_stock',
  'out_of_stock',
  'available_on_order',
  'unknown'
);

create type listing_status as enum ('draft', 'active', 'archived', 'sold');

create type fulfillment_type as enum ('pickup', 'delivery');

create type vendor_order_status as enum (
  'pending_payment',
  'paid',
  'accepted',
  'preparing',
  'ready_for_pickup',
  'out_for_delivery',
  'collected',
  'delivered',
  'completed',
  'rejected',
  'cancelled',
  'refunded',
  'disputed'
);

create type order_status as enum (
  'pending_payment',
  'payment_failed',
  'paid',
  'in_fulfilment',
  'completed',
  'partially_completed',
  'cancelled',
  'refunded',
  'disputed'
);

create type payment_status as enum ('initiated', 'pending', 'confirmed', 'failed', 'refunded');

create type verification_task_status as enum ('assigned', 'started', 'completed', 'skipped', 'flagged');

create type verification_task_type as enum (
  'shop_check',
  'product_availability',
  'price_check',
  'photo_capture',
  'follow_up',
  'discrepancy_review'
);

create type confirmation_response as enum ('available', 'sold', 'updated');

create type dispute_status as enum ('open', 'under_review', 'resolved', 'closed');

create type delivery_status as enum ('pending', 'assigned', 'picked_up', 'in_transit', 'delivered', 'failed', 'cancelled');

create type inquiry_status as enum ('open', 'answered', 'closed');

-- ---------------------------------------------------------------------------
-- Identity, profiles, roles
-- ---------------------------------------------------------------------------

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  phone text,
  email text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_roles (
  user_id uuid not null references public.profiles (id) on delete cascade,
  role app_role not null,
  created_at timestamptz not null default now(),
  primary key (user_id, role)
);

-- ---------------------------------------------------------------------------
-- Vehicle catalogue
-- ---------------------------------------------------------------------------

create table public.vehicle_makes (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table public.vehicle_models (
  id bigint generated by default as identity primary key,
  make_id bigint not null references public.vehicle_makes (id) on delete cascade,
  name text not null,
  unique (make_id, name)
);

create table public.vehicle_generations (
  id bigint generated by default as identity primary key,
  model_id bigint not null references public.vehicle_models (id) on delete cascade,
  name text not null,               -- e.g. 'New Shape', 'DBA-DE13FS'
  year_start int,
  year_end int,
  unique (model_id, name)
);

create table public.vehicle_engines (
  id bigint generated by default as identity primary key,
  generation_id bigint references public.vehicle_generations (id) on delete cascade,
  model_id bigint references public.vehicle_models (id) on delete cascade,
  name text not null,               -- e.g. '1.3 Petrol (2NZ-FE)'
  fuel_type text,                   -- petrol | diesel | hybrid | electric
  transmission text                 -- manual | automatic | cvt | any
);

create table public.customer_vehicles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  make_id bigint not null references public.vehicle_makes (id),
  model_id bigint not null references public.vehicle_models (id),
  generation_id bigint references public.vehicle_generations (id),
  engine_id bigint references public.vehicle_engines (id),
  year int,
  nickname text,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Categories
-- ---------------------------------------------------------------------------

create table public.categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.categories (id) on delete set null,
  name text not null,
  slug text not null unique,
  icon text,
  sort_order int not null default 0
);

-- ---------------------------------------------------------------------------
-- Vendors
-- ---------------------------------------------------------------------------

create table public.vendors (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references public.profiles (id) on delete set null,
  business_name text not null,
  slug text not null unique,
  description text,
  phone text,
  whatsapp text,
  email text,
  status vendor_status not null default 'pending',
  -- application fields
  contact_person text,
  physical_address text,
  operating_area text,
  city text not null default 'Harare',
  business_documents jsonb not null default '[]'::jsonb,
  payment_details jsonb not null default '{}'::jsonb,
  -- trust
  is_verified boolean not null default false,
  verified_at timestamptz,
  rating numeric(3,2),
  review_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vendor_locations (
  id uuid primary key default gen_random_uuid(),
  vendor_id uuid not null references public.vendors (id) on delete cascade,
  name text not null default 'Main shop',
  address text not null,
  area text,                        -- e.g. 'Kaguvi Street'
  city text not null default 'Harare',
  latitude numeric(9,6),
  longitude numeric(9,6),
  is_primary boolean not null default false,
  pickup_available boolean not null default true,
  pickup_instructions text,
  delivery_available boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.vendor_staff (
  id uuid primary key default gen_random_uuid(),
  vendor_id uuid not null references public.vendors (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  staff_role text not null default 'salesperson', -- manager | cashier | salesperson | storekeeper | custom
  permissions jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (vendor_id, user_id)
);

create table public.vendor_metrics (
  vendor_id uuid primary key references public.vendors (id) on delete cascade,
  stock_accuracy numeric(5,2),
  fulfilment_rate numeric(5,2),
  cancellation_rate numeric(5,2),
  avg_response_minutes numeric(10,2),
  confirmation_consistency numeric(5,2),
  verification_consistency numeric(5,2),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Products & inventory
-- ---------------------------------------------------------------------------

create table public.products (
  id uuid primary key default gen_random_uuid(),
  vendor_id uuid not null references public.vendors (id) on delete cascade,
  category_id bigint references public.categories (id) on delete set null,
  title text not null,
  description text,
  condition product_condition not null default 'used',
  price numeric(12,2) not null check (price >= 0),
  currency text not null default 'USD',
  part_number text,
  oem_number text,
  availability availability_status not null default 'unknown',
  quantity int check (quantity is null or quantity >= 0),
  status listing_status not null default 'active',
  -- freshness
  seller_updated_at timestamptz,
  seller_confirmed_at timestamptz,
  carguvi_verified_at timestamptz,
  -- logistics
  pickup_available boolean not null default true,
  delivery_available boolean not null default true,
  view_count int not null default 0,
  search_text tsvector,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index products_vendor_idx on public.products (vendor_id);
create index products_category_idx on public.products (category_id);
create index products_status_idx on public.products (status) where status = 'active';
create index products_search_idx on public.products using gin (search_text);

create table public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  url text not null,
  sort_order int not null default 0
);

create table public.product_compatibility (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  make_id bigint references public.vehicle_makes (id) on delete cascade,
  model_id bigint references public.vehicle_models (id) on delete cascade,
  generation_id bigint references public.vehicle_generations (id) on delete cascade,
  engine_id bigint references public.vehicle_engines (id) on delete cascade,
  year_start int,
  year_end int
);

create index product_compat_product_idx on public.product_compatibility (product_id);
create index product_compat_model_idx on public.product_compatibility (model_id);

create type inventory_event_type as enum (
  'created',
  'price_change',
  'availability_change',
  'quantity_change',
  'seller_confirmed',
  'carguvi_verified',
  'sold',
  'order_reserved',
  'order_released',
  'archived',
  'discrepancy_flagged'
);

create table public.inventory_events (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  actor_id uuid references public.profiles (id) on delete set null,
  event_type inventory_event_type not null,
  old_availability availability_status,
  new_availability availability_status,
  old_price numeric(12,2),
  new_price numeric(12,2),
  note text,
  created_at timestamptz not null default now()
);

create index inventory_events_product_idx on public.inventory_events (product_id);

create table public.seller_confirmations (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  vendor_id uuid not null references public.vendors (id) on delete cascade,
  confirmed_by uuid references public.profiles (id) on delete set null,
  response confirmation_response not null,
  source text not null default 'reminder', -- reminder | dashboard | demand_trigger
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Carguvi verification (enumerators)
-- ---------------------------------------------------------------------------

create table public.verification_tasks (
  id uuid primary key default gen_random_uuid(),
  enumerator_id uuid not null references public.profiles (id) on delete cascade,
  vendor_id uuid not null references public.vendors (id) on delete cascade,
  product_id uuid references public.products (id) on delete cascade,
  task_type verification_task_type not null default 'product_availability',
  status verification_task_status not null default 'assigned',
  assigned_by uuid references public.profiles (id) on delete set null,
  due_date date,
  notes text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create index verification_tasks_enum_idx on public.verification_tasks (enumerator_id, status);

create table public.carguvi_verifications (
  id uuid primary key default gen_random_uuid(),
  task_id uuid references public.verification_tasks (id) on delete set null,
  enumerator_id uuid not null references public.profiles (id) on delete set null,
  vendor_id uuid not null references public.vendors (id) on delete cascade,
  product_id uuid references public.products (id) on delete cascade,
  observed_availability availability_status,
  observed_price numeric(12,2),
  price_discrepancy boolean not null default false,
  availability_discrepancy boolean not null default false,
  notes text,
  shop_verified boolean,
  created_at timestamptz not null default now()
);

create table public.verification_photos (
  id uuid primary key default gen_random_uuid(),
  verification_id uuid not null references public.carguvi_verifications (id) on delete cascade,
  url text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Demand signals
-- ---------------------------------------------------------------------------

create table public.search_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles (id) on delete set null,
  query text not null,
  filters jsonb not null default '{}'::jsonb,
  results_count int,
  created_at timestamptz not null default now()
);

create table public.product_views (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  user_id uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.product_favourites (
  user_id uuid not null references public.profiles (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table public.inquiries (
  id uuid primary key default gen_random_uuid(),
  product_id uuid references public.products (id) on delete set null,
  vendor_id uuid not null references public.vendors (id) on delete cascade,
  user_id uuid references public.profiles (id) on delete set null,
  name text,
  contact text,
  message text not null,
  status inquiry_status not null default 'open',
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Commerce: cart, orders, payments, delivery
-- ---------------------------------------------------------------------------

create table public.carts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cart_items (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null references public.carts (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete cascade,
  quantity int not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null,
  created_at timestamptz not null default now(),
  unique (cart_id, product_id)
);

create table public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  label text,
  recipient_name text,
  phone text,
  line1 text not null,
  area text,
  city text not null default 'Harare',
  latitude numeric(9,6),
  longitude numeric(9,6),
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.profiles (id) on delete restrict,
  status order_status not null default 'pending_payment',
  currency text not null default 'USD',
  subtotal numeric(12,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  delivery_address_id uuid references public.addresses (id) on delete set null,
  customer_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vendor_orders (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  vendor_id uuid not null references public.vendors (id) on delete restrict,
  status vendor_order_status not null default 'pending_payment',
  fulfillment_type fulfillment_type not null default 'pickup',
  pickup_location_id uuid references public.vendor_locations (id) on delete set null,
  subtotal numeric(12,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  vendor_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index vendor_orders_vendor_idx on public.vendor_orders (vendor_id, status);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  vendor_order_id uuid not null references public.vendor_orders (id) on delete cascade,
  product_id uuid references public.products (id) on delete set null,
  title text not null,
  condition product_condition,
  unit_price numeric(12,2) not null,
  quantity int not null default 1
);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  provider text not null default 'mock',
  method text,                       -- ecocash | zipit | paynow | card | cash_on_pickup
  amount numeric(12,2) not null,
  currency text not null default 'USD',
  status payment_status not null default 'initiated',
  reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.payment_transactions (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid not null references public.payments (id) on delete cascade,
  event text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.deliveries (
  id uuid primary key default gen_random_uuid(),
  vendor_order_id uuid not null references public.vendor_orders (id) on delete cascade,
  provider text not null default 'carguvi_local',
  status delivery_status not null default 'pending',
  address_id uuid references public.addresses (id) on delete set null,
  fee numeric(12,2) not null default 0,
  distance_km numeric(6,2),
  tracking_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Reviews, disputes, notifications, audit, AI
-- ---------------------------------------------------------------------------

create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  vendor_order_id uuid not null references public.vendor_orders (id) on delete cascade,
  vendor_id uuid not null references public.vendors (id) on delete cascade,
  product_id uuid references public.products (id) on delete set null,
  user_id uuid not null references public.profiles (id) on delete cascade,
  rating int not null check (rating between 1 and 5),
  product_rating int check (product_rating between 1 and 5),
  vendor_rating int check (vendor_rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);

create type dispute_type as enum (
  'wrong_product',
  'unavailable_product',
  'damaged_product',
  'incorrect_description',
  'incorrect_price',
  'delivery_problem',
  'other'
);

create table public.disputes (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.orders (id) on delete set null,
  vendor_order_id uuid references public.vendor_orders (id) on delete set null,
  user_id uuid not null references public.profiles (id) on delete cascade,
  vendor_id uuid references public.vendors (id) on delete set null,
  dispute_type dispute_type not null default 'other',
  description text not null,
  status dispute_status not null default 'open',
  resolution text,
  resolved_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index notifications_user_idx on public.notifications (user_id, read_at);

create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.profiles (id) on delete set null,
  actor_role app_role,
  action text not null,
  entity_type text not null,
  entity_id text,
  previous_state jsonb,
  new_state jsonb,
  created_at timestamptz not null default now()
);

create table public.ai_events (
  id uuid primary key default gen_random_uuid(),
  kind text not null,               -- nl_search | reminder_copy | listing_assist | prioritization
  provider text,
  model text,
  prompt jsonb,
  response jsonb,
  user_id uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.platform_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

create trigger touch_profiles before update on public.profiles
  for each row execute function public.touch_updated_at();
create trigger touch_vendors before update on public.vendors
  for each row execute function public.touch_updated_at();
create trigger touch_products before update on public.products
  for each row execute function public.touch_updated_at();
create trigger touch_carts before update on public.carts
  for each row execute function public.touch_updated_at();
create trigger touch_orders before update on public.orders
  for each row execute function public.touch_updated_at();
create trigger touch_vendor_orders before update on public.vendor_orders
  for each row execute function public.touch_updated_at();
create trigger touch_payments before update on public.payments
  for each row execute function public.touch_updated_at();
create trigger touch_deliveries before update on public.deliveries
  for each row execute function public.touch_updated_at();
create trigger touch_disputes before update on public.disputes
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Product full-text search vector
-- ---------------------------------------------------------------------------

create or replace function public.products_search_vector()
returns trigger language plpgsql as $$
begin
  new.search_text :=
    setweight(to_tsvector('english', coalesce(new.title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(new.part_number, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.oem_number, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.description, '')), 'C');
  return new;
end $$;

create trigger products_search_vector_trigger
  before insert or update of title, part_number, oem_number, description
  on public.products for each row execute function public.products_search_vector();

-- ---------------------------------------------------------------------------
-- New user bootstrap: profile + customer role
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, phone, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    new.email
  )
  on conflict (id) do nothing;

  insert into public.user_roles (user_id, role)
  values (new.id, coalesce((new.raw_user_meta_data ->> 'role')::app_role, 'customer'))
  on conflict do nothing;

  insert into public.carts (user_id) values (new.id) on conflict do nothing;

  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

